### ISSUE TITLE
Implementation Status Bug

### ISSUE THREAD

**Issue by FourUnbelievableCoolKids** [WorkMAE/IntegrationFixes#1]
Can patch this issue in ClientSphere, where as if an Integration End Date is entered (Column W in RAW DATA), the Integration Status stays "Completed"?  

This is an issue in deals where we are part of a larger deal in multiple regions and policies and process do not align with ours.  This impacts Idle Deal percentage and skews TAT times, causing bad data in 2 of the 9 boxes determining score.

**Comment by WorkMAE** [comment]
This should be fixed in today's update.  Will check when I run to make sure it is working properly.

**Comment by FourUnbelievableCoolKids** [comment]
This looks good.  Appears to be working as expected. Thanks!
