### ISSUE TITLE
Correct Idle Deal metrics on User to match Manager

### ISSUE THREAD

**Issue by FourUnbelievableCoolKids** [WorkMAE/IntegrationFixes#2]
The idle deal percentage on the User dashboard doesn't match on the Manager dash.  Please review and amend filters to match.

**Comment by WorkMAE** [comment]
What should the filters be?

**Comment by FourUnbelievableCoolKids** [comment]
They should be as follows for the first set (Lines 267A and 267G in Manager Dash):
INT Manager: Slicer driven in A / All in G
INT Active Status: In-Flight
INT Team Lead: Slicer driven in A / All in G
Deal Type: Int, Maint and New Onboarding
Group: All
INT Status: Active, Interface Dev, PVT, UAT, SIT, Project Scoping, System Setup
IMP Status: Active, Not Started, On-Hold, (blank)
Mandated?: Mandated
Active INT Manager?: Active
Deal Dupe?: N
Leading?: Leading

And as follows for the second set (Lines 282A and 282G in Manager Dash):
Apples: Multiple Items (blank and Blank)
INT Manager: Slicer driven in A / All in G
INT Active Status: In-Flight
INT Team Lead: Slicer driven in A / All in G
Deal Type: Int, Maint and New Onboarding
Group: All
INT Status: Not Started, On-Hold
IMP Status: Active, Not Started, On-Hold, (blank)
Mandated?: Mandated
Active INT Manager?: Active
Deal Dupe?: N
Leading?: Leading

**Comment by WorkMAE** [comment]
Fixed
