### ISSUE TITLE
Premandates Completed is not populated in my scorcard

### ISSUE THREAD

**Issue by dsawyer70** [WorkMAE/IntegrationFixes#4]
Completed Premandates under Premandate Performance (YTD) is not populating on my user scorecard.  All zeros.  However it does appear in the manager scorecard?
[Dave Sawyer User Scorecard.docx](https://github.com/WorkMAE/IntegrationFixes/files/1497047/Dave.Sawyer.User.Scorecard.docx)

**Comment by WorkMAE** [comment]
This is now fixed.  Somehow the "Completed" filter on the PMD Result was set to blank.
