### ISSUE TITLE
Wrike Inc not showing as a completed premandate on my scorecard

### ISSUE THREAD

**Issue by dsawyer70** [WorkMAE/IntegrationFixes#5]
Wrilke Inc (PRJ_0000771242) was a premandate that I worked on.  I completed the premandate on 11/2/17 however it is not showing as a completed premandate in my scorecard.  The Premandate was converted to New Onboarding and is currently being worked on by Delecia henry from Implementation and Delphine Corian from Integration

**Comment by WorkMAE** [comment]
@FourUnbelievableCoolKids  could you please look into this?  I don't know where to look for this type of stuff in ClientSphere...

**Comment by FourUnbelievableCoolKids** [comment]
Integration Required was set to NO.  I have updated this to YES.
